// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHe4YeLUzLCXQ_dQ25BJBX1IO62ztKJ0U',
    appId: '1:1078828407882:web:598653b40e5a6faea79ab3',
    messagingSenderId: '1078828407882',
    projectId: 'revboostapp-b0307',
    authDomain: 'revboostapp-b0307.firebaseapp.com',
    storageBucket: 'revboostapp-b0307.firebasestorage.app',
    measurementId: 'G-BB2S7FB5KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE2bpyvKdx1z9OVz3sbikk1Hlm3DcykM0',
    appId: '1:1078828407882:android:fb43babbfe44b5aaa79ab3',
    messagingSenderId: '1078828407882',
    projectId: 'revboostapp-b0307',
    storageBucket: 'revboostapp-b0307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiGfUZISG-HNCr_fUl8yUPTE2HNopqfBk',
    appId: '1:1078828407882:ios:03372c6c54b36158a79ab3',
    messagingSenderId: '1078828407882',
    projectId: 'revboostapp-b0307',
    storageBucket: 'revboostapp-b0307.firebasestorage.app',
    iosBundleId: 'com.revboostapp.revboostapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiGfUZISG-HNCr_fUl8yUPTE2HNopqfBk',
    appId: '1:1078828407882:ios:03372c6c54b36158a79ab3',
    messagingSenderId: '1078828407882',
    projectId: 'revboostapp-b0307',
    storageBucket: 'revboostapp-b0307.firebasestorage.app',
    iosBundleId: 'com.revboostapp.revboostapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHe4YeLUzLCXQ_dQ25BJBX1IO62ztKJ0U',
    appId: '1:1078828407882:web:9a5f81921c70116da79ab3',
    messagingSenderId: '1078828407882',
    projectId: 'revboostapp-b0307',
    authDomain: 'revboostapp-b0307.firebaseapp.com',
    storageBucket: 'revboostapp-b0307.firebasestorage.app',
    measurementId: 'G-7BQNX9DSN9',
  );
}
